version: "3.8"

services:
  clovett_website:
    build:
      context: .
    image: clovett_website:latest
    container_name: clovett_website
    ports:
      - "5000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt


  
