version: "3.8"

services:
  clovett_website:
    build:
      context: .
    image: clovett_website:latest
    ports:
      - "5000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - clovett_website
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  
