version: "3.8"

services:
  localsite:
    image: clovett_website:latest
    container_name: clovett_website
    ports:
      - "5000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - localsite
    ports:
      - "80:80"
      - "443:443"


  
